import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClientOnly } from "./ClientOnly";
import { Container } from "./components/Container";
import { ToasterProvider } from "./providers/ToasterProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>
                <ClientOnly>
                    <ToasterProvider />
                </ClientOnly>
                <Container>{children}</Container>
            </body>
        </html>
    );
}
