import type { Metadata } from "next";
import "./globals.css";
import { ClientOnly } from "./ClientOnly";
import { Container } from "./components/Container";
import { ToasterProvider } from "./providers/ToasterProvider";
import { Navbar } from "./components/Navbar";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>
                <ClientOnly>
                    <Navbar />
                    <ToasterProvider />
                </ClientOnly>
                <Container>{children}</Container>
            </body>
        </html>
    );
}
